### ISSUE TITLE
Closing the window always dumps focus back onto the leftmost window

### ISSUE THREAD

**Issue by JonnyRa** [mileszs/ack.vim#227] opened 2017-11-01 16:59 UTC
Hi!

I frequently work with 2 buffers open with a vsplit.  After using Ack from the right window and then pressing q to close dumps me back at the top of the left window.

Its a bit annoying

Cheers

Jonny

**Comment by mboughaba** [comment] 2017-11-04 12:31
Hi

I got the same too, and indeed bit annoying

Cheers
Mo

**Comment by ches** [comment] 2017-11-05 12:00
@mboughaba's edited response covers exactly what I came here to say, thanks Mo 😄 

It is, perhaps unfortunately, standard Vim behavior with the full-width quickfix window. You could reproduce as such:

1. Disable ack.vim in your plugin manager.
2. `vim`
3. `<C-w>v`
4. `:copen`
5. `:cclose`, `<C-w>q`, or `:q`
6. You'll find the cursor back in the left split.

And yes, a workaround if you don't mind the results window not opening full-width is—as @mboughaba has pointed out—to omit `botright` from how we open the windows:

```vim
let g:ack_qhandler = 'copen'
let g:ack_lhandler = 'copen'
```

See `:help g:ack_qhandler`.

Other ideas would be to try to curb the habit of closing the quickfix window while it is selected: after you open a search result, use `:cclose` from the window of the matched file (or create a mapping for it). I use an extraction of [Dr. Mike Henry's `QuickFixWinToggle` function][1] which automatically goes back to the previous non-quickfix window with `wincmd p` if needed before closing, so it actually solves exactly this problem as well.

[1]: https://github.com/drmikehenry/vimfiles/blob/4351f6fa1f220828778d688b71d7fd5c60838c9c/vimrc#L2934-L2948

**Closed by ches** 2017-11-05 12:00 UTC

**Comment by JonnyRa** [comment] 2017-11-06 09:28
Ok, thanks for digging into this. I'll check out the link you suggested.  Is the 'q' standard to quickfix?  Do you want to keep it behaving like standard vim?  Was just thinking it might be worth changing the close behaviour anyway - I'd log it as a vim bug if you could actually do that!

**Comment by mboughaba** [comment] 2017-11-06 13:09
```vim
let g:ack_qhandler = 'copen'
```
This has extra disadvantage. If custom ack_qhandler is set in user's config, no mapping will be added by Ack.
For instance you can no longer close the quick fix by hitting 'q' on its window. 
*To me this is normal because the user is managing quickfix by overriding the default qhandler.*
