### ISSUE TITLE
Everything turns into Wingdings

### ISSUE THREAD

**Issue by xanderdunn** [mileszs/ack.vim#151] opened 2015-01-17 23:38 UTC
Mac OSX 10.10.1.  tmux 1.9a.  ack.vim latest.  vim 7.4.488.

When I search for certain things in certain directories, at a certain point all the ack output and even my preexisting vim buffer will turn entirely into wingding characters and everything will be completely unreadable.  [Screen recording](https://raw.githubusercontent.com/alexdunn/storage/master/ack_tmux_vim_wingdings.mov).

Reproduce:

1. Get the source to the [YouCompleteMe](https://github.com/Valloric/YouCompleteMe/) vim plugin and cd into the sources' directory.  I just have it installed using Vundle, so I just cd into ~/.vim/bundle/YouCompleteMe.
1. Execute:
```bash
tmux new -s test
vim
:S info
```
About midway through the search messages, everything will switch to wingdings.  

This is 100% reproducible for me in both vim and NeoVim. Indeed, it seems specific to using vim inside tmux.  This does not occur if I use vim directly in the terminal, outside of tmux.

**Comment by alexdunn** [comment] 2015-01-18 08:27
Where I have the command S defined in my .vimrc:
```
:command! -nargs=+ S :Ack! "<args>"
```

**Comment by ches** [comment] 2015-02-12 12:46
I have a somewhat similar setup (well, same tmux version at least, still on OS X 10.9 and my Vim version is a few patches behind yours, but it sounds like tmux and terminal stuff is really the heart of the matter). I open the exact same file within tmux, ran your command definition with the same search term: no problem. Could you gist your `tmux.conf`?

What's the value of `echo $TERM` in your tmux shell versus Terminal (that's Terminal and not iTerm I believe, right?)? Perhaps also `env | grep LC_`.

Also what happens if you just run `ag info` in your shell from that directory, outside Vim?

**Comment by ches** [comment] 2015-06-06 05:13
Couldn't reproduce and no further info provided, closing. Please follow up if the problem persists.

**Closed by ches** 2015-06-06 05:13 UTC

**Comment by gj** [comment] 2018-11-26 15:51
Almost four years later, but this happened to me because I had

```
set -g default-terminal 'screen-256color'
```

instead of

```
set -g default-terminal 'xterm-256color'
```

in my `tmux.conf`, with the latter matching my actual (outside of tmux) terminal.
